<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>BL0006;$(NoWarn)</NoWarn>
    <PackageId>BlazorWinUI</PackageId>
    <Authors>Sathiyaraman-M</Authors>
    <Description>Build native Windows applications with Blazor and WinUI.</Description>
    <PackageTags>blazor;windows;winui;native</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Sathiyaraman-M/BlazorWinUI</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../LICENSE" Pack="true" PackagePath="LICENSE" />
    <None Update="../../README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlazorWinUI.Generators\BlazorWinUI.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
  </ItemGroup>
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
</Project>
