<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>BL0006;$(NoWarn)</NoWarn>
    <PackageId>BlazorWinUI</PackageId>
    <Authors>Sathiyaraman-M</Authors>
    <Description>Build native Windows applications with Blazor and WinUI.</Description>
    <PackageTags>blazor;windows;winui;native</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
  </ItemGroup>
</Project>
